### ISSUE TITLE
setup error on mac OS X EI Captain

### ISSUE THREAD

**Issue by shinsyzgz** [alejandrobll/py-sphviewer#3]
I am using Anaconda 2.4.1 and tried to install the package sphviewer. However, pip, easy_install or python setup.py install gives the similar error shown below:
$easy_install py-sphviewer

Searching for py-sphviewer
Reading https://pypi.python.org/simple/py-sphviewer/
Best match: py-sphviewer 1.0.2
Downloading https://pypi.python.org/packages/source/p/py-sphviewer/py-sphviewer-1.0.2.tar.gz#md5=69f62232ace350307455afacd44bcb8e
Processing py-sphviewer-1.0.2.tar.gz
Writing /var/folders/xw/z2t4jxbj5zbg1w06wc97gc140000gn/T/easy_install-WhEmOm/py-sphviewer-1.0.2/setup.cfg
Running py-sphviewer-1.0.2/setup.py -q bdist_egg --dist-dir /var/folders/xw/z2t4jxbj5zbg1w06wc97gc140000gn/T/easy_install-WhEmOm/py-sphviewer-1.0.2/egg-dist-tmp-IfFrW8
clang: error: unsupported option '-fopenmp'

**Comment by alejandrobll** [comment]
This is not an issue with sphviewer but with the clang compiler of Mac. ""Unfortunately"" I have not a Mac to test it, but I understand that clang doesn't support openmp. Please, check this post here to see if it solves your problem http://stackoverflow.com/questions/33668323/clang-omp-in-xcode-under-el-capitan

If so, could you please send me back the solution so that I can write it in the installation instructions for Mac user?

**Comment by shinsyzgz** [comment]
The post really helps, at least I now know what the problem is.

However, I failed to get openmp working on my mac. I don’t use Xcode, I just use the X-code command line tools, so I was not able to follow the steps provided in the post. And, I am sort of an idiot on clang and gcc…

**Comment by alejandrobll** [comment]
Unfortunately, I did the code in a way that it is not straightforward to switch off OpenMP. I should change that, but in the meantime, you  could install gcc? It might not be difficult (I guess).

**Comment by shinsyzgz** [comment]
Finally got it done! Thank you!
Below are the steps I took.
1 - Install gcc using: brew install gcc --without-multilib
after about one hour, the command completed.
2. Use the command below to created a link under the path /usr/local/bin so that when I run gcc, I run gcc-5 instead of clang.
ln -s gcc-5 gcc

btw, my path variable is: /Users/Guangzhi/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
1. Finally, pip install py-sphviewer
   Done!

**Comment by alejandrobll** [comment]
Perfect. Thank you for the explanation on the steps needed.

**Comment by rubinghv** [comment]
@shinsyzgz 
I followed your instructions and installed gcc (without multilib) without an issue. However after following the next two steps I'm still getting the same error, I navigated to /usr/local/bin and created the link but it still seems to be having the same problem. 

Do you know if the clang file in there is the problem? in the sense that clang still seems to be run instead of gcc.

Also, what is the particular relevance of your path variable?
Thanks!

**Comment by shinsyzgz** [comment]
sorry for the late reply.

would you please try "which gcc" to see what command you are actually running when calling gcc? make sure it is the gcc you installed instead of clang.

**Comment by markuskreitzer** [comment]
clang-omp has been deprecated in Mac OS Sierra's version of Homebrew <http://discourse.brew.sh/t/there-is-no-longer-a-clang-omp-formula-for-macos-sierra/47>. They suggest installing llvm instead which incorporates omp functionality. I will report back if I can get this installed.

**Comment by markuskreitzer** [comment]
So far, this is what I had to do on Mac OS Sierra (with Homebrew installed)

1. [Re]move clang
2. Symlink the llvm clang version to the /usr/bin/clang path. You could probably have done this a different way if you needed the original clang to be preserved, for example, prepend the other one to the PATH.
3. Added a few things to the CPPFLAGS env var
    1. `-Wno-return-type` is needed because there's parts of the code that does `return;` which the compiler doesn't like.
    2. The numpy headers couldn't be found, so I added the `-I /usr/local/lib/python2.7/site-packages/numpy/core/include`.
    3. The rest were all found from here <http://stackoverflow.com/a/39843038/1842416>

```
brew install llvm
sudo mv /usr/bin/clang /usr/bin/clang.old
sudo ln -s /usr/local/opt/llvm/bin/clang /usr/bin/clang
export CPPFLAGS="$CPPFLAGS -Wno-return-type -I /usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/opt/llvm/include -fopenmp"
export CPP=$CPP:/usr/local/opt/llvm/bin/clang
export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm/lib"
pip2.7 install py-sphviewer
```

**Comment by markuskreitzer** [comment]
Still not working. I am now getting more errors related to the above:
```Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphviewer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sphviewer/__init__.py", line 10, in <module>
    from Particles import Particles
  File "/usr/local/lib/python2.7/site-packages/sphviewer/Particles.py", line 6, in <module>
    from pykdtree.kdtree import KDTree # pykdtree by Esben S. Nielsen 
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pykdtree/kdtree.so, 2): Library not loaded: @rpath/libomp.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/pykdtree/kdtree.so
  Reason: image not found```

**Comment by alejandrobll** [comment]
Is there anything that can be done from our side to fix this issue? Otherwise, can I close it?

**Comment by JBorrow** [comment]
Hi, everyone. Here's some instructions to get py-sphviewer; the easiest thing to do is to just compile the C extensions with gcc.

Installing PySPHViewer on MacOS

0. Install GCC and make sure it is your default compiler (you can do this with homebrew, brew install gcc. Then modify your PATH and CC environment variables). You must do this because clang does not have OpenMP support.
1. Create a new virtual environment (you can do this with python3 -m venv <name of your environment>
2. Activate the environment with <name of environment>/bin/activate
3. Install your dependencies, i.e. numpy, etc.
4. Clone a copy of PySPHViewer
5. Create a soft link to the numpy source code in <name of environment>/include. You can do this from that directory by doing ln -s ../lib/python3.6/site-packages/numpy/core/include/numpy numpy (you may need to edit this slightly based on your exact python version). You _must_ do this because the linking inside the pip installer is broken for some reason.
6. Run pip install . from inside the py-sphviewer directory.
7. You should now have PySPHViewer installed.

**Comment by JBorrow** [comment]
Addressed in #17. All that should be required, once that's merged, is to install `libomp`.

**Comment by alejandrobll** [comment]
This issue seems to be fixed in the master branch now. I'll close it.

**Comment by jlumbard** [comment]
Hi there, Apologies to pick up on an old issue but I'm having trouble with this on a mac today still. I've done brew install libomp and still get: 

`    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/include -c pykdtree/kdtree.c -o build/temp.macosx-10.9-x86_64-3.8/pykdtree/kdtree.o -std=c99 -O3 -fopenmp
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1`

I have attempted with both pip and the clone & setup.py install method. Have I missed a step, or could you recommend anything else for me to try? 

Edit for anyone looking for a workaround: https://stackoverflow.com/questions/36211018/clang-error-errorunsupported-option-fopenmp-on-mac-osx-el-capitan-buildin 

This worked for me

**Comment by alejandrobll** [comment]
It looks like you do not have the gcc compiler on your Mac. I would either try to install it, or change the compiler. Have you followed @JBorrow steps -described above- on this?
